controller_list:
  - name: arm/left
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
  # - name: arm/right
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - right_joint1
  #     - right_joint2
  #     - right_joint3
  #     - right_joint4
  #     - right_joint5
  #     - right_joint6
  #     - right_joint7
  # - name: body_controller
  #   joints:
  #     - body_joint
  # - name: hand/left
  #   action_ns: /
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - left_ee_joint
  # - name: hand/right
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - right_ee_joint
  # - name: gaze_joint1
  #   action_ns: single_joint_position
  #   type: SingleJointPosition
  #   default: true
  #   joints:
  #     - gaze_joint1
  # - name: gaze_joint2
  #   action_ns: single_joint_position
  #   type: SingleJointPosition
  #   default: true
  #   joints:
  #     - gaze_joint2
      