controller_list:
  - name: fake_arm_left_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
  - name: fake_arm_right_controller
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_left_gripper_controller
    joints:
      # - left_joint7
      - left_ee_joint
  - name: fake_right_gripper_controller
    joints:
      # - right_joint7
      - right_ee_joint
  # - name: fake_gaze_controller
  #   joints:
  #     - torso_joint
  #     - gaze_joint1
  #     - gaze_joint2
  # - name: fake_basemove_group_controller
  #   joints:
  #     - lb_wheel_joint
  #     - lf_wheel_joint
  #     - rb_wheel_joint
  #     - rf_wheel_joint