controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
  - name: fake_arms_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_right_arm_controller
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_body_controller
    joints:
      - body_joint
  - name: fake_left_grip_controller
    joints:
      - left_ee_joint
  - name: fake_right_grip_controller
    joints:
      - right_ee_joint